<template>
    <div class="footer">
        <ul class="footer-list">
            <li class="footer-list-item">
                <font-awesome-icon icon="copyright" class="list-icon" />
                <a href="https://easyconsult.ro" target="_blank"
                    >Easy Consult</a
                >
            </li>
            <li class="footer-list-item">
                <font-awesome-icon icon="code" class="list-icon" />
                Developed by: Lucian Tanase
            </li>
            <li class="footer-list-item">
                <font-awesome-icon icon="file-contract" class="list-icon" />
                <a href="#overlay-terms">{{ terms }}</a>
            </li>
            <li class="footer-list-item">
                <font-awesome-icon icon="user-shield" class="list-icon" />
                <a href="#overlay-privacy">{{ privacy }}</a>
            </li>
        </ul>

        <div id="overlay-terms">
            <div id="terms">
                <div class="terms-header">
                    <h3>{{ titleTerms }}</h3>
                    <a href="#terms" class="btn-close">&times;</a>
                </div>
                <p v-show="showEN">
                    The EasyClause web app is distributed by the Law Office
                    Tanase Lucian having its registered office in Bucharest,
                    Sector 6, 8 Aleea Arinii Dornei, block M29, entrance 1, 9th
                    floor, ap. 40, e-mail: office@easyconsult.ro, mobile:
                    +40722559703 and registered with Bucharest bar Association
                    based on decision no 2413/11.10.2007.
                </p>
                <p v-show="showRO">
                    Aplicația web EasyClause este dezvoltată și distribuită de
                    către Cabinetul de Avocat Tănase Lucian cu sediul
                    profesional în București, Sector 6, Aleea Arinii Dornei nr.
                    8, bl. M29, sc.1, etaj 9, ap. 40, email:
                    office@easyconsult.ro, mobil: +4072259703 și înființat
                    conform Deciziei Baroului București nr. 2413/11.10.2007.
                </p>
                <p v-show="showEN">
                    The web app is free to use and do not require to create an
                    account for using it. The user acknowledges and agrees that
                    the use of this app does not create any legal relationship
                    between our Law Office and the user and no legal advice of
                    any kind is provided by our Law Office to the user following
                    the use of the app.
                </p>
                <p v-show="showRO">
                    Applicatia se poate folosi în mod gratuit și nu necesită
                    crearea unui cont de utilizator. Utilizatorul ia la
                    cunostință și este de acord că prin folosirea programului de
                    completare nu ia naștere o relație juridică între Cabinetul
                    de Avocat Tanase Lucian si utilizator si instalarea si
                    folosirea programului de completare nu reprezinta acordarea
                    de asistenta juridica catre utilizator.
                </p>
                <p v-show="showEN">
                    The clauses are prepared taking into consideration their
                    legal effects in accordance with the Romanian laws. However
                    no explicit or implied warranty is offered by the Law Office
                    in respect with the adequacy of these clauses to the user's
                    purposes. The user need to seek legal advice to know what
                    their effects will be in the legal systems that covers the
                    documents where such clauses are inserted.
                </p>
                <p v-show="showRO">
                    Clauzele sunt redactate luand in considerare efectele lor in
                    baza legii romane. Cu toate acestea Cabinetul de Avocat
                    Tanase Lucian nu acorda nicio garantie explicita sau
                    implicita cu privire la adecvarea acestora pentru scopurile
                    in care sunt folosite de catre utilizator. Utilizatorul va
                    trebui sa beneficieze de asistenta juridica pentru a
                    determina efectele juridice din cadrul sistemului de drept
                    ce se aplica documentelor in care sunt folosite clauzele.
                </p>
                <p v-show="showEN">
                    The user is sole responsible for the use of the clauses
                    generated by the app and our Law Office shall not be held
                    responsible or otherwise liable for any damages or loss that
                    user may incur following the use of this web app. In the
                    extent provided by the law our law office shall be
                    exonerated by any liability concerning the use of the web
                    app by the user.
                </p>
                <p v-show="showRO">
                    Utilizatorul este singurul responsabil pentru modul in care
                    utilizeaza clauzele generate de aplicatie si biroul nostru
                    de avocatura nu va fi tinut responsabil sau in altfel
                    raspunzator pentru orice daune sau pierderi pe care
                    utilizatorul le poate suferi ca urmare a folosirii
                    aplicatiei. In masura permisa de lege biroul nostru de
                    avocatura va fi exonerat de orice raspundere legata de
                    folosirea programului de completare de catre utilizator.
                </p>
            </div>
        </div>
        <div id="overlay-privacy">
            <div id="privacy">
                <div class="privacy-header">
                    <h3>{{ titlePrivacy }}</h3>
                    <a href="#privacy" class="btn-close">&times;</a>
                </div>
                <p v-show="showEN">
                    Our web app uses third-party cookies for obtaining analytics
                    data about the manner in which the application is accessed
                    and used by the users.
                </p>
                <p v-show="showRO">
                    Aplicația noastră web folosește cookie-uri unei terțe părți
                    pentru obținerea de date analitice privind modul în care
                    aplicația este accesată și folosită de utilizatori.
                </p>
                <p v-show="showEN">
                    These cookies are placed by Google Analytics services and
                    may represents unique identifiers based on which data about
                    the traffic in and out of the app, is collected.
                </p>
                <p v-show="showRO">
                    Astfel de cookie-uri sunt plasate de serviciul de date
                    analitice Google Analytics și pot reprezenta identifcatori
                    unici pe baza cărora se colectează date privind traficul
                    înspre și dinspre aplicație.
                </p>
                <p v-show="showEN">
                    Google Analytics services provides us the analytics data in
                    anonymized format and consequently we are not processing any
                    personal data of the user and we do not have any accesss to
                    such personal data.
                </p>
                <p v-show="showRO">
                    Datele furnizate către noi de serviciul Google Analytics
                    sunt anonimizate astfel încât prin utilizarea aplicației noi
                    nu prelucrăm nicio dată personală a utilizatorului și nu
                    avem acces la asemenea date personale ale utilizatorului.
                </p>
                <p v-show="showEN">
                    The use of Google Analytics services and its related cookies
                    is made for legitimate interest of the ower of the web app,
                    respectively optimization and enhancement the performance
                    and the features of the web application, based on anonymous
                    data regarding the traffic to the web application or inside
                    it.
                </p>
                <p v-show="showRO">
                    Utilizarea serviciului Google Analytics are loc în vederea
                    intereselor legitime ale proprietarului website-ului, pentru
                    optimizarea și îmbunătățirea funcționării aplicației, pe
                    baza unui set de date anonime cu privire la modalitatea de
                    accesare a aplicației și traseul utilizatorilor în cadrul
                    acesteia.
                </p>
                <p v-show="showEN">
                    Accesing our web app is made under a secure connection using
                    an SSL certificate issued by a recognized certificate
                    authority.
                </p>
                <p v-show="showRO">
                    Accesarea aplicației noastre are loc pe baza unei conexiuni
                    securizate folosind un certificat SSL emis de o reputată
                    autoritate de certificare.
                </p>
                <p v-show="showEN">
                    For any questions related to our privacy policy you can
                    contact us using our
                    <a href="/contact">Contact</a> page.
                </p>
                <p v-show="showRO">
                    Pentru orice întrebări legate de politica noastră privind
                    datele personale ne puteți contacta prin intermediul paginii
                    noastre de <a href="/contact">Contact</a>.
                </p>
            </div>
        </div>
    </div>
</template>

<script>
export default {
    name: "Footer",
    props: {
        showEN: {
            type: Boolean
        },
        showRO: {
            type: Boolean
        }
    },
    computed: {
        titleTerms: function() {
            if (this.showEN) {
                return "Terms and Conditions";
            } else {
                return "Termeni de Utilizare ";
            }
        },

        titlePrivacy: function() {
            if (this.showEN) {
                return "Privacy Policy";
            } else {
                return "Politică Date Personale";
            }
        },
        terms: function() {
            if (this.showEN) {
                return "Terms";
            } else {
                return "Termeni";
            }
        },
        privacy: function() {
            if (this.showEN) {
                return "Privacy";
            } else {
                return "Date Personale";
            }
        }
    }
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="scss">
.footer {
    /*  margin-left: -1em;
    margin-right: -1em; */
    height: 40px;
    margin-top: 2em;
    /*color: white;*/

    &-list {
        list-style-type: none;
        text-align: center;
        margin-bottom: 0;
        display: flex;
        justify-content: center;
        align-items: baseline;
    }

    &-list-item {
        font-size: 0.9rem;
        display: inline-block;
        padding: 0.5rem 1rem;
        cursor: pointer;

        a:link,
        a:visited {
            text-decoration: none;
            color: inherit;
        }

        &:hover {
            background-color: #faf1fc;
        }
    }
}

.list-icon {
    margin-right: 0.2rem;
}

#overlay-terms,
#overlay-privacy {
    position: fixed;
    visibility: hidden;
    width: 100%;
    height: 100%;
    top: 100%;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: rgba(0, 0, 0, 0.7);
    z-index: 2;
    cursor: pointer;
    transition: all 0.5s;
}

#terms,
#privacy {
    position: absolute;
    top: 50%;
    left: 50%;
    font-size: 1rem;
    text-align: justify;
    background-color: #fff;
    padding: 1rem 2rem;
    color: navy;
    transform: translate(-50%, -50%);
    -ms-transform: translate(-50%, -50%);
    font-size: 0.8em;
}

.terms-header h3,
.privacy-header h3 {
    text-align: center;
    position: relative;
    font-size: 1.2rem;
}

.btn-close {
    position: absolute;
    top: 0;
    right: 0.5rem;
    font-size: 30px;
    text-decoration: none;
    display: block;
    float: right;
}

#overlay-terms:target,
#overlay-privacy:target {
    visibility: visible;
    top: 0;
}

/* @media (min-width: 801px) {
    .footer {
        margin-top: 2em;
        margin-bottom: 0;
        position: absolute;
        bottom: 0;
        left: 0;
        right: 0;
    }
} */

@media (max-width: 800px) {
    .footer {
        margin-top: 1rem;
        margin-left: 0;
        margin-right: 0;
        &-list {
            flex-flow: column;
            padding: 0;
            align-items: center;
        }
    }

    .terms-header h3,
    .privacy-header h3 {
        font-size: 1rem;
    }

    #terms,
    #privacy {
        width: 75%;
        overflow-y: scroll;
        font-size: 0.8rem;
        height: 100vh;
        text-align: justify;
        padding-top: 1rem;
    }
}

@media (max-width: 600px) {
    .terms-header h3,
    .privacy-header h3 {
        font-size: 0.9rem;
    }
    #terms,
    #privacy {
        width: 90%;
        font-size: 0.8rem;
    }
}
</style>
